"""Build script for creating the Windows installer.

Usage:
    python build_installer.py          # Build PyInstaller exe only
    python build_installer.py --inno   # Also build Inno Setup installer
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent
DIST = ROOT / "dist"
BUILD = ROOT / "build"
APP_NAME = "eFloStop_Production_Tool"
ICON = ROOT / "app" / "resources" / "icons" / "app.ico"


def build_exe() -> Path:
    """Build the standalone .exe using PyInstaller."""
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--name", APP_NAME,
        "--windowed",
        "--onedir",
        "--add-data", f"{ROOT / 'app' / 'config' / 'default_config.yaml'};app/config",
        "--add-data", f"{ROOT / 'app' / 'resources'};app/resources",
        "--add-data", f"{ROOT / 'firmware'};firmware",
        "--collect-all", "serial",
        "--collect-all", "esptool",
        # bleak + winrt: critical for BLE scanning. PyInstaller misses
        # winrt.windows.foundation.collections (a dynamic submodule needed
        # by bleak's WinRT scanner callback) without --collect-all winrt.
        "--collect-all", "bleak",
        "--collect-all", "winrt",
        "--hidden-import", "serial.tools.list_ports",
        "--hidden-import", "serial.tools.list_ports_windows",
        "--hidden-import", "serial.serialutil",
        "--distpath", str(DIST),
        "--workpath", str(BUILD),
    ]

    if ICON.exists():
        cmd.extend(["--icon", str(ICON)])

    cmd.append(str(ROOT / "main.py"))

    print(f"Running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)

    exe_dir = DIST / APP_NAME
    print(f"Build complete: {exe_dir}")
    return exe_dir


def build_inno_installer(exe_dir: Path) -> None:
    """Build Inno Setup installer (.exe)."""
    iss_path = ROOT / "installer.iss"
    if not iss_path.exists():
        _generate_iss(iss_path, exe_dir)

    # Find Inno Setup compiler
    iscc = Path(r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe")
    if not iscc.exists():
        iscc = Path(r"C:\Program Files\Inno Setup 6\ISCC.exe")
    if not iscc.exists():
        print("Inno Setup not found. Install from https://jrsoftware.org/isinfo.php")
        print(f"ISS file generated at: {iss_path}")
        return

    print(f"Running Inno Setup: {iscc}")
    subprocess.run([str(iscc), str(iss_path)], check=True)
    print("Installer built successfully.")


def _generate_iss(iss_path: Path, exe_dir: Path) -> None:
    """Generate the Inno Setup script."""
    content = f"""; eFloStop II Production Tool — Inno Setup Script
; Auto-generated by build_installer.py

[Setup]
AppName=eFloStop II Production Tool
AppVersion=1.0.0
AppPublisher=eFloStop
DefaultDirName={{autopf}}\\eFloStop Production Tool
DefaultGroupName=eFloStop Production Tool
OutputDir={DIST}
OutputBaseFilename=eFloStop_Production_Tool_Setup
Compression=lzma2
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64compatible

[Files]
Source: "{exe_dir}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Preserve firmware folder on upgrade — don't overwrite user-edited files
Source: "{ROOT / 'firmware'}\\*"; DestDir: "{{app}}\\firmware"; Flags: onlyifdoesntexist recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\eFloStop Production Tool"; Filename: "{{app}}\\{APP_NAME}.exe"
Name: "{{commondesktop}}\\eFloStop Production Tool"; Filename: "{{app}}\\{APP_NAME}.exe"

[Run]
Filename: "{{app}}\\{APP_NAME}.exe"; Description: "Launch eFloStop Production Tool"; Flags: nowait postinstall skipifsilent
"""
    iss_path.write_text(content, encoding="utf-8")
    print(f"Generated: {iss_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build eFloStop Production Tool")
    parser.add_argument("--inno", action="store_true", help="Also build Inno Setup installer")
    args = parser.parse_args()

    exe_dir = build_exe()

    if args.inno:
        build_inno_installer(exe_dir)
